import {
  BellSimpleIcon,
  CalendarCheckIcon,
  CalendarXIcon,
  ChatCircleDotsIcon,
  ChatTeardropTextIcon,
  CheckCircleIcon,
  ClockCountdownIcon,
  CurrencyGbpIcon,
  EyeIcon,
  FlagIcon,
  HouseLineIcon,
  PaperPlaneTiltIcon,
  ProhibitIcon,
  ReceiptIcon,
  ScalesIcon,
  SealCheckIcon,
  UsersThreeIcon,
  WarningOctagonIcon,
  WrenchIcon,
  XCircleIcon,
  type Icon,
} from '@phosphor-icons/react'
import type { NotificationKind } from '@/domain/types'

const ICONS: Record<NotificationKind, Icon> = {
  job_reported: WrenchIcon,
  job_approved: CheckCircleIcon,
  job_declined: ProhibitIcon,
  job_cancelled: XCircleIcon,
  trade_instructed: PaperPlaneTiltIcon,
  quote_received: ReceiptIcon,
  quote_accepted: CheckCircleIcon,
  quote_declined: XCircleIcon,
  quote_withdrawn: XCircleIcon,
  visit_booked: CalendarCheckIcon,
  visit_cancelled: CalendarXIcon,
  job_completed: CheckCircleIcon,
  job_confirmed: SealCheckIcon,
  payment: CurrencyGbpIcon,
  message: ChatCircleDotsIcon,
  tenancy_to_confirm: HouseLineIcon,
  tenancy_confirmed: HouseLineIcon,
  rating_open: ChatTeardropTextIcon,
  rating_reminder: ClockCountdownIcon,
  ratings_revealed: ChatTeardropTextIcon,
  review_reply: ChatTeardropTextIcon,
  review_update: ChatTeardropTextIcon,
  review_disputed: ScalesIcon,
  report_update: FlagIcon,
  document_due_soon: ClockCountdownIcon,
  document_expired: WarningOctagonIcon,
  passport_viewed: EyeIcon,
  verification_checked: SealCheckIcon,
  team_invite: UsersThreeIcon,
}

export function notificationIcon(kind: NotificationKind): Icon {
  return ICONS[kind] ?? BellSimpleIcon
}
